name: OCPP.Core

services:
  # Sinlge container with both servers
  ocpp-core:
    image: ocpp.core:latest
    container_name: ocpp.core
    build:
      context: .
      tags:
        - latest
    ports:
      - "47532:8081"
      - "47533:8082"
    volumes:
      - sqlite:/db
    environment:
      # Change your API Key to something long and obscure (must match on server and management)
      ApiKey: xxxx
      ConnectionStrings__SQLite: "Filename=/db/OCPP.Core.sqlite;"
      #ConnectionStrings__SqlServer:
      MessageDumpDir: /tmp/ocpp/
      Logging__LogLevel__OCPP: "Information"
      Logging__LogLevel__Default: "Information"
      DOTNET_ENVIRONMENT: Production
      ASPNETCORE_ENVIRONMENT: Production
      # Management UI calls the server within the same container via localhost
      ServerApiUrl: http://localhost:8081/API
      # Management UI users (add more with Users__1__*, Users__2__* etc.)
      Users__0__Username: admin
      Users__0__Password: t3st
      Users__0__Administrator: true
    restart: unless-stopped

volumes:
  # SQLite database is stored in the ./SQLite folder next to compose.yaml
  # Remember to initialise the database before starting for the first time
  sqlite:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./SQLite
