name: OCPP.Core

services:
  # Sinlge container with both servers
  ocpp-core:
    image: ocpp.core:latest
    container_name: ocpp.core
    build:
      context: .
      tags:
        - latest
    ports:
      - "47532:8081"
      - "47533:8082"
    volumes:
      - sqlite:/db
    environment:
      # --- Required changes for production ---
      # Set a long random string; must match on server and management side
      ApiKey: ""
      # --- Optional overrides (defaults are set in the image) ---
      #ConnectionStrings__SQLite: "Filename=/db/OCPP.Core.sqlite;"
      #ConnectionStrings__SqlServer: ""
      #MessageDumpDir: /tmp/ocpp/
      #Logging__LogLevel__Default: "Information"
    restart: unless-stopped

volumes:
  # SQLite database is stored in the ./SQLite folder next to compose.yaml
  # Remember to initialise the database before starting for the first time
  sqlite:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./SQLite
