USE [master]
GO
/****** Object:  Database [OCPP.Core]    Script Date: 20.12.2020 22:54:30 ******/
CREATE DATABASE [OCPP.Core]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OCCP.Core', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\OCCP.Core.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OCCP.Core_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\OCCP.Core_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [OCPP.Core] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OCPP.Core].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OCPP.Core] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OCPP.Core] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OCPP.Core] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OCPP.Core] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OCPP.Core] SET ARITHABORT OFF 
GO
ALTER DATABASE [OCPP.Core] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OCPP.Core] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OCPP.Core] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OCPP.Core] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OCPP.Core] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OCPP.Core] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OCPP.Core] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OCPP.Core] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OCPP.Core] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OCPP.Core] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OCPP.Core] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OCPP.Core] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OCPP.Core] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OCPP.Core] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OCPP.Core] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OCPP.Core] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OCPP.Core] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OCPP.Core] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OCPP.Core] SET  MULTI_USER 
GO
ALTER DATABASE [OCPP.Core] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OCPP.Core] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OCPP.Core] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OCPP.Core] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OCPP.Core] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OCPP.Core] SET QUERY_STORE = OFF
GO
USE [OCPP.Core]
GO
/****** Object:  Table [dbo].[ChargePoint]    Script Date: 20.12.2020 22:54:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChargePoint](
	[ChargePointId] [nvarchar](100) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Comment] [nvarchar](200) NULL,
 CONSTRAINT [PK_ChargePoint_1] PRIMARY KEY CLUSTERED 
(
	[ChargePointId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ChargeTags]    Script Date: 20.12.2020 22:54:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ChargeTags](
	[TagId] [nvarchar](50) NOT NULL,
	[TagName] [nvarchar](200) NULL,
	[ParentTagId] [nvarchar](50) NULL,
	[ExpiryDate] [datetime2](7) NULL,
	[Blocked] [bit] NULL,
 CONSTRAINT [PK_ChargeKeys] PRIMARY KEY CLUSTERED 
(
	[TagId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MessageLog]    Script Date: 20.12.2020 22:54:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MessageLog](
	[LogId] [int] IDENTITY(1,1) NOT NULL,
	[LogTime] [datetime2](7) NOT NULL,
	[ChargePointId] [nvarchar](100) NOT NULL,
	[ConnectorId] [int] NULL,
	[Message] [nvarchar](100) NOT NULL,
	[Result] [nvarchar](max) NULL,
	[ErrorCode] [nvarchar](100) NULL,
 CONSTRAINT [PK_MessageLog] PRIMARY KEY CLUSTERED 
(
	[LogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transactions]    Script Date: 20.12.2020 22:54:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[TransactionId] [int] IDENTITY(1,1) NOT NULL,
	[ChargePointId] [nvarchar](100) NOT NULL,
	[ConnectorId] [int] NOT NULL,
	[StartTagId] [nvarchar](50) NULL,
	[StartTime] [datetime2](7) NOT NULL,
	[MeterStart] [int] NOT NULL,
	[StartResult] [nvarchar](100) NULL,
	[StopTagId] [nvarchar](50) NULL,
	[StopTime] [datetime2](7) NULL,
	[MeterStop] [int] NULL,
	[StopReason] [nvarchar](100) NULL,
 CONSTRAINT [PK_Transactions] PRIMARY KEY CLUSTERED 
(
	[TransactionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [ChargePoint_Identifier]    Script Date: 20.12.2020 22:54:30 ******/
CREATE UNIQUE NONCLUSTERED INDEX [ChargePoint_Identifier] ON [dbo].[ChargePoint]
(
	[ChargePointId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_MessageLog_ChargePointId]    Script Date: 20.12.2020 22:54:30 ******/
CREATE NONCLUSTERED INDEX [IX_MessageLog_ChargePointId] ON [dbo].[MessageLog]
(
	[LogTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_ChargePoint] FOREIGN KEY([ChargePointId])
REFERENCES [dbo].[ChargePoint] ([ChargePointId])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_ChargePoint]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_Transactions] FOREIGN KEY([TransactionId])
REFERENCES [dbo].[Transactions] ([TransactionId])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_Transactions]
GO
USE [master]
GO
ALTER DATABASE [OCPP.Core] SET  READ_WRITE 
GO
